services:
  web:
    image: node:25
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "${WEB_PORT}:3000"
    environment:
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
    command: npm run dev
    depends_on:
      - db
    tty: true

  db:
    image: mysql:9.5
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
